language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
script:
    - "python setup.py test"
notifications:
  email:
    recipients:
      - sebastianr213@gmail.com
      - sebasrodriguez_89@hotmail.com
    on_success: change
    on_failure: always